version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      zabbix:
        ipv4_address: 172.20.1.11
networks:
  zabbix:
    ipam:
      config:
        - subnet: 172.20.1.0/24
